# Generated by Django 5.1.3 on 2025-02-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_offer', '0003_alter_client_email_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
